### ISSUE TITLE
Rechtschreibfehler in "Unsuppoted Operation"

### ISSUE THREAD

**Issue by horoscloud** [pachermichael/iwi15calc_GruppeB#1]
"Unsuppoted Operation" sollte zu "Unsupported Operation" geändert werden.

**Comment by XiangjunWu** [comment]
Do you have any screenshots?

**Comment by horoscloud** [comment]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/80542238/202728962-178edf7d-8acc-4f58-ac25-0e430cb69878.png">

**Comment by XiangjunWu** [comment]
Thank you! I will continue analyse!

**Comment by XiangjunWu** [comment]
Dev done. Please retest it. I will close this ticket @horoscloud

**Comment by pachermichael** [comment]
Noch nicht alles umgesetzt.
